import { useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { toast } from 'sonner'
import { QrCode } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { useCreateQRCode, useCheckQRCode } from '@/hooks/use-login'
import { LoginLayout } from '@/components/layout/login-layout'
import { Button } from '@/components/ui/button'
import { LoadingSpinner } from '@/components/layout/loading-spinner'

type QRStatus = 'idle' | 'created' | 'scanned' | 'confirmed' | 'expired'

const ACCENT = 'oklch(0.48 0.16 265)'

export function LoginQRCodePage() {
  const navigate = useNavigate()
  const { t } = useTranslation()
  const createQR = useCreateQRCode()
  const checkQR = useCheckQRCode()
  const [qrImage, setQrImage] = useState<string | null>(null)
  const [status, setStatus] = useState<QRStatus>('idle')
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null)

  const STATUS_CONFIG: Record<QRStatus, { label: string; color: string }> = {
    idle: { label: '', color: 'var(--muted-foreground)' },
    created: { label: t('web.qrcode_waiting', 'Waiting for scan…'), color: 'var(--muted-foreground)' },
    scanned: { label: t('web.qrcode_scanned', 'Scanned — confirming…'), color: 'var(--accent)' },
    confirmed: { label: t('web.qrcode_confirmed', 'Confirmed!'), color: 'var(--accent)' },
    expired: { label: t('web.qrcode_expired', 'QR code expired'), color: 'var(--destructive)' },
  }

  function stopPolling() {
    if (pollRef.current) {
      clearInterval(pollRef.current)
      pollRef.current = null
    }
  }

  function startPolling() {
    stopPolling()
    pollRef.current = setInterval(() => {
      checkQR.mutate(undefined, {
        onSuccess: (data) => {
          if (data.status === 'confirmed') {
            stopPolling()
            setStatus('confirmed')
            navigate('/finish')
          } else if (data.status === 'expired') {
            stopPolling()
            setStatus('expired')
            toast.error('QR code expired. Please generate a new one.')
          } else if (data.status === 'scanned') {
            setStatus('scanned')
          }
        },
        onError: () => {
          stopPolling()
          setStatus('expired')
        },
      })
    }, 3000)
  }

  function handleGenerate() {
    createQR.mutate(undefined, {
      onSuccess: (data) => {
        setQrImage(data.image_base64)
        setStatus('created')
        startPolling()
      },
      onError: (err) => {
        toast.error(err instanceof Error ? err.message : 'Failed to generate QR code')
      },
    })
  }

  useEffect(() => {
    return () => stopPolling()
  }, [])

  const statusConfig = STATUS_CONFIG[status]
  const showQR = qrImage && status !== 'expired'

  return (
    <LoginLayout
      panel={{
        accentColor: ACCENT,
        hero: (
          <div
            className="flex h-16 w-16 items-center justify-center rounded-2xl"
            style={{
              background: `color-mix(in oklch, ${ACCENT} 15%, var(--background))`,
              border: `1px solid color-mix(in oklch, ${ACCENT} 30%, transparent)`,
            }}
          >
            <QrCode size={28} style={{ color: ACCENT }} />
          </div>
        ),
        eyebrow: 'Miyoushe',
        title: t('web.qrcode_title', 'QR Code Login'),
        description:
          'Generate a QR code and scan it with the Miyoushe mobile app to log in instantly — no password required.',
        features: ['Passwordless', 'Miyoushe App', 'Auto-refresh'],
        securityNote:
          'The QR code is generated by Miyoushe servers and expires after a short time. No credentials are stored on our servers.',
      }}
    >
      <div className="flex flex-col gap-8 stagger-children">
        {/* Header */}
        <div className="flex flex-col gap-1">
          <div className="flex items-center gap-3 mb-1">
            <img src="/images/miyoushe.webp" alt="Miyoushe" className="h-8 w-8 rounded-lg object-cover" />
            <span className="text-xs font-medium tracking-widest uppercase text-muted-foreground">
              Miyoushe
            </span>
          </div>
          <h1
            className="text-2xl font-semibold tracking-tight text-foreground"
            style={{ fontFamily: 'var(--font-display)' }}
          >
            {t('web.qrcode_title', 'QR Code Login')}
          </h1>
          <p className="text-sm text-muted-foreground">
            {t('web.qrcode_desc', 'Scan the QR code with the Miyoushe app')}
          </p>
        </div>

        {/* QR Code area */}
        <div className="flex flex-col items-center gap-5">
          <div
            className="relative flex h-52 w-52 items-center justify-center rounded-2xl border-2 overflow-hidden transition-all duration-300"
            style={{
              borderColor: showQR
                ? 'color-mix(in oklch, var(--accent) 40%, var(--border))'
                : 'var(--border)',
              background: showQR ? 'var(--card)' : 'var(--muted)',
            }}
          >
            {showQR ? (
              <img
                src={`data:image/png;base64,${qrImage}`}
                alt="QR Code"
                className="h-full w-full object-contain p-3"
              />
            ) : createQR.isPending ? (
              <LoadingSpinner size={32} />
            ) : (
              <div className="flex flex-col items-center gap-2 text-center px-4">
                <div
                  className="h-10 w-10 rounded-xl flex items-center justify-center text-xl"
                  style={{ background: 'color-mix(in oklch, var(--accent) 12%, transparent)' }}
                >
                  📱
                </div>
                <p className="text-xs text-muted-foreground leading-relaxed">
                  {t('web.qrcode_placeholder', 'Generate a QR code to scan with Miyoushe')}
                </p>
              </div>
            )}
          </div>

          {/* Status indicator */}
          {status !== 'idle' && (
            <div className="flex items-center gap-2">
              {(status === 'created' || status === 'scanned') && (
                <LoadingSpinner size={14} />
              )}
              <span
                className="text-sm font-medium transition-colors duration-300"
                style={{ color: statusConfig.color }}
              >
                {statusConfig.label}
              </span>
            </div>
          )}

          {/* Actions */}
          <div className="flex flex-col gap-2 w-full">
            {(status === 'idle' || status === 'expired') && (
              <Button
                onClick={handleGenerate}
                disabled={createQR.isPending}
                className="w-full h-10 font-semibold"
                style={{ fontFamily: 'var(--font-display)' }}
              >
                {status === 'expired'
                  ? t('web.qrcode_regenerate', 'Regenerate QR Code')
                  : t('web.qrcode_generate', 'Generate QR Code')}
              </Button>
            )}
            <button
              type="button"
              onClick={() => navigate(-1)}
              className="text-xs text-muted-foreground hover:text-foreground transition-colors duration-150 text-center py-1"
            >
              {t('web.back', '← Back')}
            </button>
          </div>
        </div>
      </div>
    </LoginLayout>
  )
}
